#!/bin/bash

BRANCHES=$(git branch --list dev | rev | cut -d' ' -f1 | rev)

if [ $# -ne 0 ]; then
  echo "Syntax: git branch-dev-rebase-main"
  exit
fi

git checkout main
git-fetch-update

for br in $BRANCHES; do
	git checkout $br
	git rebase -i main
done

