#!/bin/bash


if [ $# -ne 1 ]; then
  echo "Syntax: git branch-rebase-all <branch-pattern>"
  exit
fi

PATTERN=$1

BRANCHES=$(git branch --list $PATTERN* | rev | cut -d' ' -f1 | rev)

git checkout main
git-fetch-update

for br in $BRANCHES; do
	read -p "Rebase $br? [Y/n]: " opt
	case $opt in
	    [Nn]* ) echo "Skipping..."; continue;;
	esac
	git checkout $br
	git rebase main
done

